### ISSUE TITLE
exporting a group from property type group

### ISSUE THREAD

**Issue by quimarche** [hackolade/JSONCustomProperties#1]
Using the following entityLevelConfig.json:

[
	{
		"lowerTab": "Details",
		"structure": [
			{
				"propertyKeyword": "uniqueKeys",
				"propertyName": "Unique keys",
				"propertyType": "group",
				"structure": [
					{
						"propertyKeyword": "uniqueKey",
						"propertyName": "Unique key",
						"propertyType": "tagInput",
						"template": "collectiontree"
					}
				]
			}
		]
	}
]

How do I export the field(s) when forward engineering the JSON schema?

**Comment by pdesmarets** [comment]
If you're on version v3.6.2 or above of the Hackolade application, you should not need this plugin any longer.  Customization is handled differently and is documented here: https://hackolade.com/help/Userdefinedcustomproperties.html

If I understand your question correctly, you'd like your custom properties to appear when you forward-engineer JSON Schema.  This is done by selecting "Extended":
![image](https://user-images.githubusercontent.com/10139210/80213504-8f150a00-8639-11ea-9996-b6475b8f3582.png)

**Comment by quimarche** [comment]
Yes, I've seen that. My output, using the custom property described above, is:

"uniqueKeys": [
        {
            "id": "22f79980-8627-11ea-a357-d153441181dd",
            "uniqueKey": [
                {
                    "type": "",
                    "keyId": "f411c500-8612-11ea-92e5-fbace3a0f25b"
                }
            ]
        },
        {
            "id": "25ca4180-8627-11ea-a357-d153441181dd",
            "uniqueKey": [
                {
                    "type": "",
                    "keyId": "f90be0e0-8612-11ea-92e5-fbace3a0f25b"
                }
            ]
        }
    ],

What I really want is the empty "type": "" fields to contain the name of the field. In other words, the field I select in the properties pane needs to be exported when forward engineered.

**Comment by pdesmarets** [comment]
Can we move the conversation to support@hackolade.com so you could send me the model file and the whole file entityLevelConfig.json ?  I'm having a hard time visualizing the input in the model and why the type is empty.  This should be working fine.  Thanks
